### ISSUE TITLE
Make the logo of DIREC have a transparent background

### ISSUE THREAD

**Issue by rafaelcn** [UTFPR-SH/direc#12]
The task is to take the logo image of DIREC, located on `assets/img/logos/direc.png` and remove the black background, making it usable with a variety of backgrounds.

**Comment by jcardoz** [comment]
taking this up

**Comment by jcardoz** [comment]
@rafaelcn - added the updated image here
https://github.com/UTFPR-SH/direc/pull/17

**Comment by jcardoz** [comment]
@rafaelcn can you take a look

**Comment by rafaelcn** [comment]
Sorry for the absence. I will take a look.
