### ISSUE TITLE
Centralize pictures of the index page

### ISSUE THREAD

**Issue by rafaelcn** [UTFPR-SH/direc#2]
The pictures on the index.html page are on left side of the screen, leaving an unpleasant design. They should be centralized respective to the content of the page.

**Comment by Jose-27** [comment]
can you be more specific? are you referring the the carousel images?

**Comment by rafaelcn** [comment]
No, I'm referring to the tile images on the top of the page.

**Comment by Jose-27** [comment]
@rafaelcn pull request created

**Comment by rafaelcn** [comment]
Fixed with #11.
